### ISSUE TITLE
Data.Random.Lift is an abomination

### ISSUE THREAD

**Issue by treeowl** [haskell-numerics/random-fu#47]
I happened into that module by chance and was rather grossed out. I'm curious whether it really needs to be there/that way, or whether there's something less horrifying that can accomplish whatever its purpose is. Even using a closed type family to select instances by hand would be less horrible.

**Comment by idontgetoutmuch** [comment]
I am intrigued - could you be more explicit about the nature of the grossness? I doubt we will get a response from the original author. I use this library a lot and maintain it when time permits. If you have suggestions for its improvement w am eager to hear them.

**Comment by idontgetoutmuch** [comment]
Without further information there is not a lot I can do - please feel free to re-open.

**Comment by int-e** [comment]
For what it's worth, `{-# LANGUAGE IncoherentInstances #-}` is enough to gross *me* out. And using closed type families for instance selection sounds like a possible solution for that, so perhaps that's what @treeowl meant as well.
