### ISSUE TITLE
wrong git tag for random-source 0.3.0.11

### ISSUE THREAD

**Issue by teto** [haskell-numerics/random-fu#84]
https://hackage.haskell.org/package/random-source shows an upper-bound of < 4.16 for release 0.3.0.11 while the rs-0.3.0.11 tag on github shows < 5 see
https://github.com/haskell-numerics/random-fu/blob/42c72183a65c429230ad9d006534f59a6b72a329/random-source/random-source.cabal#L69

**Comment by idontgetoutmuch** [comment]
https://hackage.haskell.org/package/random-source-0.3.0.11/revisions/ - I don't know why this was done - *but* `random-source` is now no longer needed for `random-fu` and I am going to offer maintainership to anyone who would like to take it on on the libraries mailing list. If no-one takes up the offer I will mark it as deprecated.

**Comment by teto** [comment]
are you bodigrim or did someone else just changed the package ?! I had no idea one could do that sry ^^''
I was updating one project that relies on random-source apparently. Am I able to ditch it and use random-fu instead (I am an indirect user of the library so not rally familiar yet)

**Comment by idontgetoutmuch** [comment]
I am **not** bodigrim - there is a "feature" on package that allows authorised folks to change e.g. bounds on packages without having to get the library maintainer to make a release.

You might have to modify your code to use the latest version of `random-fu` (which is faster BTW). Let me know if I can help.
