### ISSUE TITLE
Confusion with sample types

### ISSUE THREAD

**Issue by samuelrivas** [haskell-numerics/random-fu#90]
I am trying to update some old code that doesn't compile with the latest version of random fu, but I am a bit confused about how is `sample` working now.

From the docs and the code I see that its type is so I should be able to sample an RVar having a stateful generator

```
(Random.Sampleable d m t, Random.StatefulGen g m,
   MonadReader g m) =>
  d t -> m t
        -- Defined in `Data.Random.Sample'
```

Which is what `:i` also returns in `ghci`. However `:t` returns a different type, which makes sampling an `RVar` a bit more unclear:

```
> :i Random.sample 
Random.sample ::
  (Random.Sampleable d m t, Random.StatefulGen g m,
   MonadReader g m) =>
  d t -> m t
        -- Defined in `Data.Random.Sample'
> :t Random.sample
Random.sample
  :: (Random.Distribution d t, Random.StatefulGen g m,
      MonadReader g m) =>
     d t -> m t
```

Can someone explain what is going on here?

**Comment by idontgetoutmuch** [comment]
Just in case you need an example, I put one here: https://github.com/haskell-numerics/random-fu/issues/83#issuecomment-1114591775

**Comment by idontgetoutmuch** [comment]
I think the difference between what `:i` returns and `:t` returns is a question for ghc.

**Comment by samuelrivas** [comment]
Great, thanks. I'll take a look.

**Comment by samuelrivas** [comment]
For the record, I got [an answer](https://stackoverflow.com/questions/74938617/how-can-i-show-a-different-type-than-t/74942805#74942805) for the difference between `:t` and `:i`. In short, `:t` runs type inference, and simplifies `Sampleable` out with the instance for `Distribution`, `:i` on the other hand reports the type that is written in the source code, without running inference on it.
